-- AlterTable
ALTER TABLE `IPInfo` ADD COLUMN `userId` VARCHAR(191) NOT NULL DEFAULT '0';

-- AddForeignKey
ALTER TABLE `IPInfo` ADD CONSTRAINT `IPInfo_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
